// Generated by CoffeeScript 1.7.1
(function() {
  var Gist,
    __slice = [].slice;

  Gist = (function() {
    function Gist(client) {
      this.client = client;
    }

    Gist.prototype.list = function() {
      var cb, params, _i, _ref;
      params = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), cb = arguments[_i++];
      return (_ref = this.client).get.apply(_ref, ["/gists"].concat(__slice.call(params), [function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('Gist list error'));
        } else {
          return cb(null, b, h);
        }
      }]));
    };

    Gist.prototype["public"] = function() {
      var cb, params, _i, _ref;
      params = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), cb = arguments[_i++];
      return (_ref = this.client).get.apply(_ref, ["/gists/public"].concat(__slice.call(params), [function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('Gist public error'));
        } else {
          return cb(null, b, h);
        }
      }]));
    };

    Gist.prototype.starred = function() {
      var cb, params, _i, _ref;
      params = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), cb = arguments[_i++];
      return (_ref = this.client).get.apply(_ref, ["/gists/starred"].concat(__slice.call(params), [function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('Gist starred error'));
        } else {
          return cb(null, b, h);
        }
      }]));
    };

    Gist.prototype.user = function() {
      var cb, params, user, _i, _ref;
      params = 3 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 2) : (_i = 0, []), user = arguments[_i++], cb = arguments[_i++];
      return (_ref = this.client).get.apply(_ref, ["/users/" + user + "/gists"].concat(__slice.call(params), [function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('Gist user error'));
        } else {
          return cb(null, b, h);
        }
      }]));
    };

    Gist.prototype.get = function(id, cb) {
      return this.client.get("/gists/" + id, function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('Gist get error'));
        } else {
          return cb(null, b, h);
        }
      });
    };

    Gist.prototype.create = function(gist, cb) {
      return this.client.post("/gists", gist, function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 201) {
          return cb(new Error('Gist create error'));
        } else {
          return cb(null, b, h);
        }
      });
    };

    Gist.prototype.edit = function(id, gist, cb) {
      return this.client.post("/gists/" + id, gist, function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('Gist edit error'));
        } else {
          return cb(null, b, h);
        }
      });
    };

    Gist.prototype["delete"] = function(id) {
      return this.client.del("/gists/" + id, {}, (function(_this) {
        return function(err, s, b, h) {
          if ((err != null) || s !== 204) {
            return _this["delete"](id);
          }
        };
      })(this));
    };

    Gist.prototype.fork = function(id) {
      return this.client.post("/gists/" + id + "/forks", {}, function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 201) {
          return cb(new Error('Gist fork error'));
        } else {
          return cb(null, b, h);
        }
      });
    };

    Gist.prototype.star = function(id) {
      return this.client.put("/gists/" + id + "/star", {}, (function(_this) {
        return function(err, s, b, h) {
          if ((err != null) || s !== 204) {
            return _this.star(id);
          }
        };
      })(this));
    };

    Gist.prototype.unstar = function(id) {
      return this.client.del("/gists/" + id + "/unstar", {}, (function(_this) {
        return function(err, s, b, h) {
          if ((err != null) || s !== 204) {
            return _this.unstar(id);
          }
        };
      })(this));
    };

    Gist.prototype.check = function(id) {
      return this.client.get("/gists/" + id + "/star", function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        return cb(null, s === 204, h);
      });
    };

    Gist.prototype.listComments = function(id, cb) {
      return this.client.get("/gists/" + id + "/comments", function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('Gist comments error'));
        } else {
          return cb(null, b, h);
        }
      });
    };

    Gist.prototype.getComment = function(id, cb) {
      return this.client.get("/gists/comments/" + id, function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('Gist getComment error'));
        } else {
          return cb(null, b, h);
        }
      });
    };

    Gist.prototype.createComment = function(id, comment, cb) {
      return this.client.post("/gists/" + id + "/comments", comment, function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 201) {
          return cb(new Error('Gist createComment error'));
        } else {
          return cb(null, b, h);
        }
      });
    };

    Gist.prototype.updateComment = function(id, comment, cb) {
      return this.client.post("/gists/comments/" + id, comment, function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('Gist updateComment error'));
        } else {
          return cb(null, b, h);
        }
      });
    };

    Gist.prototype.deleteComment = function(id) {
      return this.client.del("/gists/comments/" + id, {}, (function(_this) {
        return function(err, s, b, h) {
          if ((err != null) || s !== 204) {
            return _this.deleteComment(id);
          }
        };
      })(this));
    };

    Gist.prototype.comments = function(id, cbOrCmnt, cb) {
      if ((cb == null) && typeof cbOrCmnt === 'function') {
        return this.listComments(id, cbOrCmnt);
      } else {
        return this.createComment(id, cbOrCmnt, cb);
      }
    };

    Gist.prototype.comment = function(cbOrIdOrCmnt, cbOrCmnt, cb) {
      if ((cb == null) && typeof cbOrIdOrCmnt === 'number' && typeof cbOrCmnt === 'function') {
        return this.getComment(cbOrIdOrCmnt, cbOrCmnt);
      } else if ((cbOrCmnt == null) && (cb == null) && typeof cbOrIdOrCmnt === 'number') {
        return this.deleteComment(cbOrIdOrCmnt);
      } else if (typeof cb === 'function' && typeof cbOrIdOrCmnt === 'number' && typeof cbOrCmnt('object')) {
        return this.updateComment(cbOrIdOrCmnt, cbOrCmnt, cb);
      } else {
        return cbOrIdOrCmnt(new Error('Gist comment error'));
      }
    };

    return Gist;

  })();

  module.exports = Gist;

}).call(this);
