// Generated by CoffeeScript 1.6.3
(function() {
  var Issue;

  Issue = (function() {
    function Issue(repo, number, client) {
      this.repo = repo;
      this.number = number;
      this.client = client;
    }

    Issue.prototype.comments = function(cb) {
      return this.client.get("/repos/" + this.repo + "/issues/" + this.number + "/comments", function(err, s, b) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('Issue Comments error'));
        } else {
          return cb(null, b);
        }
      });
    };

    return Issue;

  })();

  module.exports = Issue;

}).call(this);
