// Generated by CoffeeScript 1.4.0
(function() {
  var Pr;

  Pr = (function() {

    function Pr(repo, number, client) {
      this.repo = repo;
      this.number = number;
      this.client = client;
    }

    Pr.prototype.info = function(cb) {
      return this.client.get("/repos/" + this.repo + "/pulls/" + this.number, function(err, s, b) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error("Pr info error"));
        } else {
          return cb(null, b);
        }
      });
    };

    Pr.prototype.update = function(obj, cb) {
      return this.client.post("/repos/" + this.repo + "/pulls/" + this.number, obj, function(err, s, b) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error("Pr update error"));
        } else {
          return cb(null, b);
        }
      });
    };

    Pr.prototype.close = function(cb) {
      return this.update({
        state: 'closed'
      }, cb);
    };

    Pr.prototype.merged = function(cb) {
      return this.client.get("/repos/" + this.repo + "/pulls/" + this.number + "/merge", function(err, s, b) {
        if (err && err.message === 'null') {
          return cb(null, false);
        }
        if (s !== 204) {
          return cb(new Error("Pr merged error"));
        } else {
          return cb(null, true);
        }
      });
    };

    Pr.prototype.merge = function(msg, cb) {
      return this.client.put("/repos/" + this.repo + "/pulls/" + this.number + "/merge", {
        commit_message: msg
      }, function(err, s, b) {
        if (err) {
          return cb(err);
        }
        return cb(null, b);
      });
    };

    Pr.prototype.commits = function(cb) {
      return this.client.get("/repos/" + this.repo + "/pulls/" + this.number + "/commits", function(err, s, b) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error("Pr commits error"));
        } else {
          return cb(null, b);
        }
      });
    };

    Pr.prototype.files = function(cb) {
      return this.client.get("/repos/" + this.repo + "/pulls/" + this.number + "/files", function(err, s, b) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error("Pr files error"));
        } else {
          return cb(null, b);
        }
      });
    };

    return Pr;

  })();

  module.exports = Pr;

}).call(this);
