// Generated by CoffeeScript 1.9.3
(function() {
  var Release;

  Release = (function() {
    function Release(repo, number, client) {
      this.repo = repo;
      this.number = number;
      this.client = client;
    }

    Release.prototype.info = function(cb) {
      return this.client.get("/repos/" + this.repo + "/releases/" + this.number, function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error("Release info error"));
        } else {
          return cb(null, b, h);
        }
      });
    };

    Release.prototype.assets = function(uploadHost, name, file, contentType, cb) {
      var options;
      options = {
        params: {
          name: name
        },
        body: file,
        headers: {
          'Content-Type': contentType
        }
      };
      return this.client.post("https://" + uploadHost + "/repos/" + this.repo + "/releases/" + this.number + "/assets", null, options, function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 201) {
          return cb(new Error("Release assets error"));
        } else {
          return cb(null, b, h);
        }
      });
    };

    return Release;

  })();

  module.exports = Release;

}).call(this);
