// Generated by CoffeeScript 1.12.7
(function() {
  var Base, Search,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  Search = (function(superClass) {
    extend(Search, superClass);

    function Search(client) {
      this.client = client;
    }

    Search.prototype.issues = function(params, cb) {
      return this.client.get("/search/issues", params, function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('Search issues error'));
        } else {
          return cb(null, b, h);
        }
      });
    };

    Search.prototype.repos = function(params, cb) {
      return this.client.get("/search/repositories", params, function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('Search repos error'));
        } else {
          return cb(null, b, h);
        }
      });
    };

    Search.prototype.users = function(params, cb) {
      return this.client.get("/search/users", params, function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('Search users error'));
        } else {
          return cb(null, b, h);
        }
      });
    };

    Search.prototype.code = function(params, cb) {
      return this.client.get("/search/code", params, function(err, s, b, h) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('Search email error'));
        } else {
          return cb(null, b, h);
        }
      });
    };

    return Search;

  })(Base);

  module.exports = Search;

}).call(this);
