// Generated by CoffeeScript 1.12.7
(function() {
  var octonode;

  octonode = module.exports = {
    auth: require('./octonode/auth'),
    client: require('./octonode/client'),
    user: require('./octonode/user'),
    repo: require('./octonode/repo'),
    org: require('./octonode/org'),
    pr: require('./octonode/pr'),
    team: require('./octonode/team'),
    release: require('./octonode/release'),
    gist: require('./octonode/gist'),
    search: require('./octonode/search'),
    issue: require('./octonode/issue'),
    project: require('./octonode/project'),
    milestone: require('./octonode/milestone'),
    label: require('./octonode/label'),
    me: require('./octonode/me')
  };

}).call(this);
